title = "Eric's Nerons"
baseURL = "https://epl692.github.io"
languageCode = "en-us"
theme = "hugo-theme-terminal"
resourceDir = "../resources"
publishDir = "docs"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 7 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[languages]
  [languages.en]
    title = "Eric's Nerons"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will
  # automatically get the last updated
  showLastUpdated = false

  text_color = ""
  author = "Eric Lynema"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/epl692"
